### ISSUE TITLE
Asciidoctor Report should be reusable

### ISSUE THREAD

**Issue by obfischer** [jQAssistant/jqa-asciidoc-report-plugin#1]
**As user** of the Asciidoctor Plugin for jQAssistant, 
**I want do be able to share or to reuse an existing report** as I can do it already with any kind of rules, 
**so that I am able to define and provide consistant reports** for multiple projects.

**Comment by DirkMahler** [comment]
index.adoc files which are placed in plugins under the path `META-INF/jqassistant-rules` or any sub-folder of it are now automatically rendered. Furthermore relative includes are supported.
