### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by hmozaffari** [jQAssistant/jqa-asciidoc-report-plugin#16]
How can I disable asciidoc plugin if I don't need it? It seem even though I don't use it, it executes Graphviz and "dot.exe" executable file on my machine. I have some limitation and don't want to execute third party none-Java applications.

**Comment by DirkMahler** [comment]
There's currently no way of de-activating a plugin but this is under discussion. Does the graphviz check break your build or is it just an ugly warning which is logged?

**Comment by hmozaffari** [comment]
Thanks for looking into it. No, fortunately it doesn’t stop the analysis and skips the error. There are anti-virus programs which pop messages saying script attempts to run unknown dot.exe executable and prevent it of being executed.

**Comment by DirkMahler** [comment]
Relates to #15.

**Comment by StephanPirnbaum** [comment]
With jQAssistant 2.0, this plugin will not be part of the core distribution anymore. So this issue will be solved.
See new repo for this plugin: https://github.com/jqassistant-plugin/jqassistant-asciidoc-report-plugin
