### ISSUE TITLE
Migrate the Plugin Documentation of the AsciiDoc Report Plugin to the new Reference Manual

### ISSUE THREAD

**Issue by obfischer** [jQAssistant/jqa-asciidoc-report-plugin#8]
### Task Description

Migrate the existing documentation of the AsciiDoc Report Plugin to the new reference manul.

### Definition of Done for the Implementers
- [ ] The reference manual contains the same information as the old user manual
- [ ] The section on the AsciiDoc Report Plugin in the old user manual points to the section for the plugin in the reference manual

**Comment by StephanPirnbaum** [comment]
Closing this issue because the plugin moves out of the core distrubtion with jQA 2.0
