### ISSUE TITLE
Improve control on table layout for rule results

### ISSUE THREAD

**Issue by DirkMahler** [jQAssistant/jqa-asciidoc-report-plugin#9]
### Feature Description

Tables are the default visualization for concept and constraint results. Currently there's no control on the layout of the tables, i.e. a large number of rows or columns (or long values in columns) break the layout of the rendered document.

Therefore the ways of controlloing the table layout shall be improved, e.g. by supporting options for horizontal or vertical scrolling (e.g. as descrivbed in https://stackoverflow.com/questions/58639752/asciidoctor-overflow-on-a-large-table).

### Definition of Done for the Implementers

- [ ] We got a final feedback from the reporting user (_if applicable_)
- [ ] Unittests have been written (_if applicable_)
- [ ] Integration tests have been written (_if applicable_)
- [ ] Test coverage is the same or even better then before (_if applicable_)
- [ ] Documentation has been written (_if applicable_)
- [ ] Added a note on the new feature to the release notes (_if applicable_)

**Comment by StephanPirnbaum** [comment]
Continued at https://github.com/jqassistant-plugin/jqassistant-asciidoc-report-plugin/issues/2
